#!/bin/bash
# spsox is a simple bash script that creates spectrograms from flac files.
# Copyright (C) 2019  Ewol
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Requires Bash and SoX

here(){
find . -maxdepth 1 -type f -name "*.flac" -execdir sh -c 'sox "$1" -n remix 1 spectrogram -t "${1%.flac}" -X 500 -y 1025 -z 120 -w Kaiser -S 1:00 -d 0:02 -o "${1%.flac}.zoomed.png" \
&& echo "${1%.flac}.zoomed.png" \
&& sox "$1" -n remix 1 spectrogram -t "${1%.flac}" -x 3000 -y 513 -z 120 -w Kaiser -o "${1%.flac}.full.png" \
&& echo "${1%.flac}.full.png" \
&& mkdir -p specs \
&& mv "${1%.flac}.zoomed.png"* specs/ \
&& mv "${1%.flac}.full.png"* specs/' Cvt {} \;
}

if [[ $1 == "" ]]; then
    here;
    exit;
fi

#arguements that I don't entirely understand how they work
args=( "${@}" )

directory="${args[$(( ${#args[@]} - 1 ))]%/}"
#Shows the version of spsox. Pretty irrelevant

showVersion(){
echo spsox 0.2
}

#Runs spsox recursively. spsox -r directory

recursive(){
find "${directory}" -type f -name "*.flac" -execdir sh -c 'sox "$1" -n remix 1 spectrogram -t "${1%.flac}" -X 500 -y 1025 -z 120 -w Kaiser -S 1:00 -d 0:02 -o "${1%.flac}.zoomed.png" \
&& echo "${1%.flac}.zoomed.png" \
&& sox "$1" -n remix 1 spectrogram -t "${1%.flac}" -x 3000 -y 513 -z 120 -w Kaiser -o "${1%.flac}.full.png" \
&& echo "${1%.flac}.full.png" \
&& mkdir -p specs \
&& mv "${1%.flac}.zoomed.png"* specs/ \
&& mv "${1%.flac}.full.png"* specs/' Cvt {} \;
}

showHelp() {
cat << EOF
Usage: spsox [-hvr]

Options   Meaning

spsox     Will run in the current directory.

-r        Runs recursively. Requires a directory to be specified then *should* work on all folders and subfolders.

-h        Displays the text you're reading now.

-v        Displays the version of the script. Rather pointless, but oh well.

EOF
# EOF
}

# $@ is all command line parameters passed to the script.
# -o is for short options like -v
# -l is for long options with double dash like --version
# the comma separates different long options
# -a is for long options with single dash like -version
options=$(getopt -l "help,version,recursive" -o "hvr" -a -- "$@")

# set --:
# If no arguments follow this option, then the positional parameters are unset. Otherwise, the positional parameters
# are set to the arguments, even if some of them begin with a ‘-’.
eval set -- "$options"

while true
do
case $1 in
-h|--help)
    showHelp
    exit 0
    ;;
-c|--current)
    current
    exit 0
    ;;
-r|--recursive)
    recursive
    exit 0
    ;;
-v|--version)
    showVersion
    exit 0
    ;;
--)
    shift
    break;;
esac
shift
done
